name: InvisibleFrames
version: 2.0.0
main: com.example.invisibleframes.InvisibleFrames
api-version: '1.21'
description: Toggle item frame visibility with Shears + Shift
author: GitHub Build
website: https://github.com

permissions:
  invisibleframes.use:
    description: Toggle frame visibility
    default: true
  invisibleframes.interact:
    description: Interact with invisible frames
    default: op
  invisibleframes.break:
    description: Break invisible frames
    default: op
